# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'board.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from widgets.clickable_groupbox import ClickableGroupBox

import ui.whirl_rc

class Ui_BoardWidget(object):
    def setupUi(self, BoardWidget):
        if not BoardWidget.objectName():
            BoardWidget.setObjectName(u"BoardWidget")
        BoardWidget.resize(1420, 758)
        BoardWidget.setMinimumSize(QSize(1420, 758))
        BoardWidget.setMaximumSize(QSize(1420, 758))
        self.verticalLayout = QVBoxLayout(BoardWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.board = QFrame(BoardWidget)
        self.board.setObjectName(u"board")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.board.sizePolicy().hasHeightForWidth())
        self.board.setSizePolicy(sizePolicy)
        self.board.setStyleSheet(u"#board {\n"
"background-image: url(:/img/img/board.png);\n"
"}")
        self.board.setFrameShape(QFrame.StyledPanel)
        self.board.setFrameShadow(QFrame.Raised)
        self.queue_2 = QFrame(self.board)
        self.queue_2.setObjectName(u"queue_2")
        self.queue_2.setGeometry(QRect(78, 164, 78, 78))
        self.queue_2.setMinimumSize(QSize(78, 78))
        self.queue_2.setMaximumSize(QSize(78, 78))
        self.queue_2.setFrameShape(QFrame.StyledPanel)
        self.queue_2.setFrameShadow(QFrame.Raised)
        self.layout_queue_2 = QHBoxLayout(self.queue_2)
        self.layout_queue_2.setSpacing(3)
        self.layout_queue_2.setObjectName(u"layout_queue_2")
        self.layout_queue_2.setContentsMargins(0, 0, 0, 0)
        self.queue_4 = QFrame(self.board)
        self.queue_4.setObjectName(u"queue_4")
        self.queue_4.setGeometry(QRect(595, 86, 78, 78))
        self.queue_4.setMinimumSize(QSize(78, 78))
        self.queue_4.setMaximumSize(QSize(78, 78))
        self.queue_4.setFrameShape(QFrame.StyledPanel)
        self.queue_4.setFrameShadow(QFrame.Raised)
        self.layout_queue_4 = QHBoxLayout(self.queue_4)
        self.layout_queue_4.setSpacing(3)
        self.layout_queue_4.setObjectName(u"layout_queue_4")
        self.layout_queue_4.setContentsMargins(0, 0, 0, 0)
        self.queue_5 = QFrame(self.board)
        self.queue_5.setObjectName(u"queue_5")
        self.queue_5.setGeometry(QRect(770, 85, 162, 78))
        self.queue_5.setMinimumSize(QSize(160, 78))
        self.queue_5.setMaximumSize(QSize(165, 78))
        self.queue_5.setFrameShape(QFrame.StyledPanel)
        self.queue_5.setFrameShadow(QFrame.Raised)
        self.layout_queue_5 = QHBoxLayout(self.queue_5)
        self.layout_queue_5.setSpacing(5)
        self.layout_queue_5.setObjectName(u"layout_queue_5")
        self.layout_queue_5.setContentsMargins(0, 0, 0, 0)
        self.queue_6 = QFrame(self.board)
        self.queue_6.setObjectName(u"queue_6")
        self.queue_6.setGeometry(QRect(1247, 325, 78, 240))
        self.queue_6.setMinimumSize(QSize(78, 240))
        self.queue_6.setMaximumSize(QSize(78, 312))
        self.queue_6.setFrameShape(QFrame.StyledPanel)
        self.queue_6.setFrameShadow(QFrame.Raised)
        self.layout_queue_6 = QVBoxLayout(self.queue_6)
        self.layout_queue_6.setSpacing(5)
        self.layout_queue_6.setObjectName(u"layout_queue_6")
        self.layout_queue_6.setContentsMargins(0, 0, 0, 0)
        self.queue_7 = QFrame(self.board)
        self.queue_7.setObjectName(u"queue_7")
        self.queue_7.setGeometry(QRect(784, 580, 237, 78))
        self.queue_7.setMinimumSize(QSize(237, 78))
        self.queue_7.setMaximumSize(QSize(237, 78))
        self.queue_7.setFrameShape(QFrame.StyledPanel)
        self.queue_7.setFrameShadow(QFrame.Raised)
        self.layout_queue_7 = QHBoxLayout(self.queue_7)
        self.layout_queue_7.setSpacing(5)
        self.layout_queue_7.setObjectName(u"layout_queue_7")
        self.layout_queue_7.setContentsMargins(0, 0, 0, 0)
        self.queue_1 = QFrame(self.board)
        self.queue_1.setObjectName(u"queue_1")
        self.queue_1.setGeometry(QRect(160, 580, 468, 78))
        self.queue_1.setMinimumSize(QSize(324, 78))
        self.queue_1.setMaximumSize(QSize(600, 78))
        self.queue_1.setFrameShape(QFrame.StyledPanel)
        self.queue_1.setFrameShadow(QFrame.Raised)
        self.layout_queue_1 = QHBoxLayout(self.queue_1)
        self.layout_queue_1.setSpacing(5)
        self.layout_queue_1.setObjectName(u"layout_queue_1")
        self.layout_queue_1.setContentsMargins(0, 0, 0, 0)
        self.pallet_2 = QFrame(self.board)
        self.pallet_2.setObjectName(u"pallet_2")
        self.pallet_2.setGeometry(QRect(240, 85, 78, 78))
        self.pallet_2.setMinimumSize(QSize(78, 78))
        self.pallet_2.setMaximumSize(QSize(78, 78))
        self.pallet_2.setFrameShape(QFrame.StyledPanel)
        self.pallet_2.setFrameShadow(QFrame.Raised)
        self.layout_pallet_2 = QHBoxLayout(self.pallet_2)
        self.layout_pallet_2.setSpacing(3)
        self.layout_pallet_2.setObjectName(u"layout_pallet_2")
        self.layout_pallet_2.setContentsMargins(0, 0, 0, 0)
        self.pallet_3 = QFrame(self.board)
        self.pallet_3.setObjectName(u"pallet_3")
        self.pallet_3.setGeometry(QRect(441, 86, 78, 78))
        self.pallet_3.setMinimumSize(QSize(78, 78))
        self.pallet_3.setMaximumSize(QSize(78, 78))
        self.pallet_3.setFrameShape(QFrame.StyledPanel)
        self.pallet_3.setFrameShadow(QFrame.Raised)
        self.layout_pallet_3 = QHBoxLayout(self.pallet_3)
        self.layout_pallet_3.setSpacing(3)
        self.layout_pallet_3.setObjectName(u"layout_pallet_3")
        self.layout_pallet_3.setContentsMargins(0, 0, 0, 0)
        self.pallet_4 = QFrame(self.board)
        self.pallet_4.setObjectName(u"pallet_4")
        self.pallet_4.setGeometry(QRect(680, 86, 78, 78))
        self.pallet_4.setMinimumSize(QSize(78, 78))
        self.pallet_4.setMaximumSize(QSize(78, 78))
        self.pallet_4.setFrameShape(QFrame.StyledPanel)
        self.pallet_4.setFrameShadow(QFrame.Raised)
        self.layout_pallet_4 = QHBoxLayout(self.pallet_4)
        self.layout_pallet_4.setSpacing(3)
        self.layout_pallet_4.setObjectName(u"layout_pallet_4")
        self.layout_pallet_4.setContentsMargins(0, 0, 0, 0)
        self.pallet_5 = QFrame(self.board)
        self.pallet_5.setObjectName(u"pallet_5")
        self.pallet_5.setGeometry(QRect(940, 86, 78, 78))
        self.pallet_5.setMinimumSize(QSize(78, 78))
        self.pallet_5.setMaximumSize(QSize(78, 78))
        self.pallet_5.setFrameShape(QFrame.StyledPanel)
        self.pallet_5.setFrameShadow(QFrame.Raised)
        self.layout_pallet_5 = QHBoxLayout(self.pallet_5)
        self.layout_pallet_5.setSpacing(3)
        self.layout_pallet_5.setObjectName(u"layout_pallet_5")
        self.layout_pallet_5.setContentsMargins(0, 0, 0, 0)
        self.pallet_6 = QFrame(self.board)
        self.pallet_6.setObjectName(u"pallet_6")
        self.pallet_6.setGeometry(QRect(1144, 579, 78, 78))
        self.pallet_6.setMinimumSize(QSize(78, 78))
        self.pallet_6.setMaximumSize(QSize(78, 78))
        self.pallet_6.setFrameShape(QFrame.StyledPanel)
        self.pallet_6.setFrameShadow(QFrame.Raised)
        self.layout_pallet_6 = QHBoxLayout(self.pallet_6)
        self.layout_pallet_6.setSpacing(3)
        self.layout_pallet_6.setObjectName(u"layout_pallet_6")
        self.layout_pallet_6.setContentsMargins(0, 0, 0, 0)
        self.pallet_7 = QFrame(self.board)
        self.pallet_7.setObjectName(u"pallet_7")
        self.pallet_7.setGeometry(QRect(695, 578, 78, 78))
        self.pallet_7.setMinimumSize(QSize(78, 78))
        self.pallet_7.setMaximumSize(QSize(78, 78))
        self.pallet_7.setFrameShape(QFrame.StyledPanel)
        self.pallet_7.setFrameShadow(QFrame.Raised)
        self.layout_pallet_7 = QHBoxLayout(self.pallet_7)
        self.layout_pallet_7.setSpacing(3)
        self.layout_pallet_7.setObjectName(u"layout_pallet_7")
        self.layout_pallet_7.setContentsMargins(0, 0, 0, 0)
        self.pallet_1 = QFrame(self.board)
        self.pallet_1.setObjectName(u"pallet_1")
        self.pallet_1.setGeometry(QRect(77, 307, 78, 78))
        self.pallet_1.setMinimumSize(QSize(78, 78))
        self.pallet_1.setMaximumSize(QSize(80, 80))
        self.pallet_1.setFrameShape(QFrame.StyledPanel)
        self.pallet_1.setFrameShadow(QFrame.Raised)
        self.layout_pallet_1 = QHBoxLayout(self.pallet_1)
        self.layout_pallet_1.setSpacing(3)
        self.layout_pallet_1.setObjectName(u"layout_pallet_1")
        self.layout_pallet_1.setContentsMargins(0, 0, 0, 0)
        self.groupBox_1 = ClickableGroupBox(self.board)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setGeometry(QRect(160, 440, 122, 90))
        font = QFont()
        font.setPointSize(12)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"}\n"
"ClickableGroupBox:hover {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.current_5 = QLabel(self.groupBox_1)
        self.current_5.setObjectName(u"current_5")
        font1 = QFont()
        font1.setFamily(u"Owners XNarrow")
        font1.setPointSize(14)
        font1.setBold(False)
        font1.setWeight(50)
        self.current_5.setFont(font1)
        self.current_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.current_5)

        self.error_5 = QLabel(self.groupBox_1)
        self.error_5.setObjectName(u"error_5")
        font2 = QFont()
        font2.setFamily(u"Owners XNarrow Black")
        font2.setPointSize(12)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setWeight(50)
        self.error_5.setFont(font2)
        self.error_5.setStyleSheet(u"color: rgb(170, 0, 0);")
        self.error_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_2.addWidget(self.error_5)

        self.groupBox_2 = ClickableGroupBox(self.board)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(230, 162, 121, 90))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.current_grease = QLabel(self.groupBox_2)
        self.current_grease.setObjectName(u"current_grease")
        self.current_grease.setFont(font1)
        self.current_grease.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.current_grease)

        self.error_grease = QLabel(self.groupBox_2)
        self.error_grease.setObjectName(u"error_grease")
        self.error_grease.setFont(font2)
        self.error_grease.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.error_grease.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.error_grease)

        self.groupBox_3 = ClickableGroupBox(self.board)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(430, 165, 150, 90))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_4 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.current_1 = QLabel(self.groupBox_3)
        self.current_1.setObjectName(u"current_1")
        self.current_1.setFont(font1)
        self.current_1.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.current_1)

        self.error_1 = QLabel(self.groupBox_3)
        self.error_1.setObjectName(u"error_1")
        self.error_1.setFont(font2)
        self.error_1.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.error_1.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.error_1)

        self.groupBox_4 = ClickableGroupBox(self.board)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(670, 165, 150, 90))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_5 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.current_2 = QLabel(self.groupBox_4)
        self.current_2.setObjectName(u"current_2")
        self.current_2.setFont(font1)
        self.current_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.current_2)

        self.error_2 = QLabel(self.groupBox_4)
        self.error_2.setObjectName(u"error_2")
        self.error_2.setFont(font2)
        self.error_2.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.error_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.error_2)

        self.groupBox_5 = ClickableGroupBox(self.board)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(930, 165, 150, 90))
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_6 = QVBoxLayout(self.groupBox_5)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.current_3 = QLabel(self.groupBox_5)
        self.current_3.setObjectName(u"current_3")
        self.current_3.setFont(font1)
        self.current_3.setAlignment(Qt.AlignCenter)

        self.verticalLayout_6.addWidget(self.current_3)

        self.error_3 = QLabel(self.groupBox_5)
        self.error_3.setObjectName(u"error_3")
        self.error_3.setFont(font2)
        self.error_3.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.error_3.setAlignment(Qt.AlignCenter)

        self.verticalLayout_6.addWidget(self.error_3)

        self.groupBox_6 = ClickableGroupBox(self.board)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(1070, 486, 170, 90))
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_7 = QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.current_4 = QLabel(self.groupBox_6)
        self.current_4.setObjectName(u"current_4")
        self.current_4.setFont(font1)
        self.current_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_7.addWidget(self.current_4)

        self.error_4 = QLabel(self.groupBox_6)
        self.error_4.setObjectName(u"error_4")
        self.error_4.setFont(font2)
        self.error_4.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.error_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_7.addWidget(self.error_4)

        self.groupBox_7 = ClickableGroupBox(self.board)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(700, 486, 170, 90))
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet(u"ClickableGroupBox {\n"
"  color: rgb(0, 0, 200);\n"
"  cursor: pointer;\n"
"}\n"
"")
        self.verticalLayout_8 = QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.current_final_test = QLabel(self.groupBox_7)
        self.current_final_test.setObjectName(u"current_final_test")
        self.current_final_test.setFont(font1)
        self.current_final_test.setAlignment(Qt.AlignCenter)

        self.verticalLayout_8.addWidget(self.current_final_test)

        self.label = QLabel(self.board)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 270, 120, 118))
        self.label.setPixmap(QPixmap(u":/img/img/robot.png"))
        self.label_2 = QLabel(self.board)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(430, 290, 120, 118))
        self.label_2.setPixmap(QPixmap(u":/img/img/robot_left.png"))
        self.label_3 = QLabel(self.board)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(670, 290, 120, 118))
        self.label_3.setPixmap(QPixmap(u":/img/img/robot_left.png"))
        self.label_4 = QLabel(self.board)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(900, 290, 120, 118))
        self.label_4.setPixmap(QPixmap(u":/img/img/robot_left.png"))
        self.label_5 = QLabel(self.board)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1090, 290, 120, 118))
        self.label_5.setPixmap(QPixmap(u":/img/img/robot_left.png"))
        self.label_6 = QLabel(self.board)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(200, 250, 71, 21))
        font3 = QFont()
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setWeight(75)
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_7 = QLabel(self.board)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(460, 270, 71, 21))
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_8 = QLabel(self.board)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(700, 270, 71, 21))
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_9 = QLabel(self.board)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(930, 270, 71, 21))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.label_10 = QLabel(self.board)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1120, 270, 71, 21))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"color: rgb(85, 170, 0);")
        self.btn_robot_play_5 = QToolButton(self.board)
        self.btn_robot_play_5.setObjectName(u"btn_robot_play_5")
        self.btn_robot_play_5.setGeometry(QRect(180, 390, 41, 41))
        self.btn_robot_play_5.setStyleSheet(u"border: none;")
        icon = QIcon()
        icon.addFile(u":/img/img/start.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_robot_play_5.setIcon(icon)
        self.btn_robot_play_5.setIconSize(QSize(40, 40))
        self.btn_robot_play_1 = QToolButton(self.board)
        self.btn_robot_play_1.setObjectName(u"btn_robot_play_1")
        self.btn_robot_play_1.setGeometry(QRect(440, 410, 41, 41))
        self.btn_robot_play_1.setStyleSheet(u"border: none;")
        self.btn_robot_play_1.setIcon(icon)
        self.btn_robot_play_1.setIconSize(QSize(40, 40))
        self.btn_robot_play_2 = QToolButton(self.board)
        self.btn_robot_play_2.setObjectName(u"btn_robot_play_2")
        self.btn_robot_play_2.setGeometry(QRect(680, 410, 41, 41))
        self.btn_robot_play_2.setStyleSheet(u"border: none;")
        self.btn_robot_play_2.setIcon(icon)
        self.btn_robot_play_2.setIconSize(QSize(40, 40))
        self.btn_robot_play_3 = QToolButton(self.board)
        self.btn_robot_play_3.setObjectName(u"btn_robot_play_3")
        self.btn_robot_play_3.setGeometry(QRect(920, 410, 41, 41))
        self.btn_robot_play_3.setStyleSheet(u"border: none;")
        self.btn_robot_play_3.setIcon(icon)
        self.btn_robot_play_3.setIconSize(QSize(40, 40))
        self.btn_robot_play_4 = QToolButton(self.board)
        self.btn_robot_play_4.setObjectName(u"btn_robot_play_4")
        self.btn_robot_play_4.setGeometry(QRect(1100, 410, 41, 41))
        self.btn_robot_play_4.setStyleSheet(u"border: none;")
        self.btn_robot_play_4.setIcon(icon)
        self.btn_robot_play_4.setIconSize(QSize(40, 40))
        self.btn_robot_more_1 = QToolButton(self.board)
        self.btn_robot_more_1.setObjectName(u"btn_robot_more_1")
        self.btn_robot_more_1.setGeometry(QRect(490, 410, 41, 41))
        self.btn_robot_more_1.setStyleSheet(u"border: none;")
        icon1 = QIcon()
        icon1.addFile(u":/img/img/more.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_robot_more_1.setIcon(icon1)
        self.btn_robot_more_1.setIconSize(QSize(40, 40))
        self.btn_robot_more_2 = QToolButton(self.board)
        self.btn_robot_more_2.setObjectName(u"btn_robot_more_2")
        self.btn_robot_more_2.setGeometry(QRect(730, 410, 41, 41))
        self.btn_robot_more_2.setStyleSheet(u"border: none;")
        self.btn_robot_more_2.setIcon(icon1)
        self.btn_robot_more_2.setIconSize(QSize(40, 40))
        self.btn_robot_more_3 = QToolButton(self.board)
        self.btn_robot_more_3.setObjectName(u"btn_robot_more_3")
        self.btn_robot_more_3.setGeometry(QRect(970, 410, 41, 41))
        self.btn_robot_more_3.setStyleSheet(u"border: none;")
        self.btn_robot_more_3.setIcon(icon1)
        self.btn_robot_more_3.setIconSize(QSize(40, 40))
        self.btn_robot_more_4 = QToolButton(self.board)
        self.btn_robot_more_4.setObjectName(u"btn_robot_more_4")
        self.btn_robot_more_4.setGeometry(QRect(1150, 410, 41, 41))
        self.btn_robot_more_4.setStyleSheet(u"border: none;")
        self.btn_robot_more_4.setIcon(icon1)
        self.btn_robot_more_4.setIconSize(QSize(40, 40))
        self.btn_robot_more_5 = QToolButton(self.board)
        self.btn_robot_more_5.setObjectName(u"btn_robot_more_5")
        self.btn_robot_more_5.setGeometry(QRect(230, 390, 41, 41))
        self.btn_robot_more_5.setStyleSheet(u"border: none;")
        self.btn_robot_more_5.setIcon(icon1)
        self.btn_robot_more_5.setIconSize(QSize(40, 40))
        self.btn_robot_error_1 = QToolButton(self.board)
        self.btn_robot_error_1.setObjectName(u"btn_robot_error_1")
        self.btn_robot_error_1.setEnabled(False)
        self.btn_robot_error_1.setGeometry(QRect(540, 410, 41, 41))
        self.btn_robot_error_1.setStyleSheet(u"border: none;")
        icon2 = QIcon()
        icon2.addFile(u":/img/img/error.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_robot_error_1.setIcon(icon2)
        self.btn_robot_error_1.setIconSize(QSize(40, 40))
        self.btn_robot_error_2 = QToolButton(self.board)
        self.btn_robot_error_2.setObjectName(u"btn_robot_error_2")
        self.btn_robot_error_2.setEnabled(False)
        self.btn_robot_error_2.setGeometry(QRect(780, 410, 41, 41))
        self.btn_robot_error_2.setStyleSheet(u"border: none;")
        self.btn_robot_error_2.setIcon(icon2)
        self.btn_robot_error_2.setIconSize(QSize(40, 40))
        self.btn_robot_error_3 = QToolButton(self.board)
        self.btn_robot_error_3.setObjectName(u"btn_robot_error_3")
        self.btn_robot_error_3.setEnabled(False)
        self.btn_robot_error_3.setGeometry(QRect(1020, 410, 41, 41))
        self.btn_robot_error_3.setStyleSheet(u"border: none;")
        self.btn_robot_error_3.setIcon(icon2)
        self.btn_robot_error_3.setIconSize(QSize(40, 40))
        self.btn_robot_error_4 = QToolButton(self.board)
        self.btn_robot_error_4.setObjectName(u"btn_robot_error_4")
        self.btn_robot_error_4.setEnabled(False)
        self.btn_robot_error_4.setGeometry(QRect(1200, 410, 41, 41))
        self.btn_robot_error_4.setStyleSheet(u"border: none;")
        self.btn_robot_error_4.setIcon(icon2)
        self.btn_robot_error_4.setIconSize(QSize(40, 40))
        self.btn_robot_error_5 = QToolButton(self.board)
        self.btn_robot_error_5.setObjectName(u"btn_robot_error_5")
        self.btn_robot_error_5.setEnabled(False)
        self.btn_robot_error_5.setGeometry(QRect(280, 390, 41, 41))
        self.btn_robot_error_5.setStyleSheet(u"border: none;")
        self.btn_robot_error_5.setIcon(icon2)
        self.btn_robot_error_5.setIconSize(QSize(40, 40))
        self.btn_ff_lower_housing = QToolButton(self.board)
        self.btn_ff_lower_housing.setObjectName(u"btn_ff_lower_housing")
        self.btn_ff_lower_housing.setGeometry(QRect(2, 307, 71, 61))
        icon3 = QIcon()
        icon3.addFile(u":/img/img/components/lower_housing.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_lower_housing.setIcon(icon3)
        self.btn_ff_lower_housing.setIconSize(QSize(65, 35))
        self.btn_ff_lower_housing.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_left_handle = QToolButton(self.board)
        self.btn_ff_left_handle.setObjectName(u"btn_ff_left_handle")
        self.btn_ff_left_handle.setGeometry(QRect(890, 20, 71, 61))
        icon4 = QIcon()
        icon4.addFile(u":/img/img/components/left_handle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_left_handle.setIcon(icon4)
        self.btn_ff_left_handle.setIconSize(QSize(65, 35))
        self.btn_ff_left_handle.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_dial = QToolButton(self.board)
        self.btn_ff_dial.setObjectName(u"btn_ff_dial")
        self.btn_ff_dial.setGeometry(QRect(965, 20, 71, 61))
        icon5 = QIcon()
        icon5.addFile(u":/img/img/components/dial.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_dial.setIcon(icon5)
        self.btn_ff_dial.setIconSize(QSize(65, 35))
        self.btn_ff_dial.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_support_arm = QToolButton(self.board)
        self.btn_ff_support_arm.setObjectName(u"btn_ff_support_arm")
        self.btn_ff_support_arm.setGeometry(QRect(1040, 20, 71, 61))
        icon6 = QIcon()
        icon6.addFile(u":/img/img/components/support_arm.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_support_arm.setIcon(icon6)
        self.btn_ff_support_arm.setIconSize(QSize(65, 35))
        self.btn_ff_support_arm.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_trigger = QToolButton(self.board)
        self.btn_ff_trigger.setObjectName(u"btn_ff_trigger")
        self.btn_ff_trigger.setGeometry(QRect(1115, 20, 71, 61))
        icon7 = QIcon()
        icon7.addFile(u":/img/img/components/trigger.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_trigger.setIcon(icon7)
        self.btn_ff_trigger.setIconSize(QSize(65, 35))
        self.btn_ff_trigger.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_right_handle = QToolButton(self.board)
        self.btn_ff_right_handle.setObjectName(u"btn_ff_right_handle")
        self.btn_ff_right_handle.setGeometry(QRect(1072, 660, 71, 61))
        icon8 = QIcon()
        icon8.addFile(u":/img/img/components/right_handle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_right_handle.setIcon(icon8)
        self.btn_ff_right_handle.setIconSize(QSize(65, 35))
        self.btn_ff_right_handle.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_hopper = QToolButton(self.board)
        self.btn_ff_hopper.setObjectName(u"btn_ff_hopper")
        self.btn_ff_hopper.setGeometry(QRect(1147, 660, 71, 61))
        icon9 = QIcon()
        icon9.addFile(u":/img/img/components/hopper.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_hopper.setIcon(icon9)
        self.btn_ff_hopper.setIconSize(QSize(65, 35))
        self.btn_ff_hopper.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_agitator = QToolButton(self.board)
        self.btn_ff_agitator.setObjectName(u"btn_ff_agitator")
        self.btn_ff_agitator.setGeometry(QRect(1222, 660, 71, 61))
        icon10 = QIcon()
        icon10.addFile(u":/img/img/components/agitator.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_agitator.setIcon(icon10)
        self.btn_ff_agitator.setIconSize(QSize(65, 35))
        self.btn_ff_agitator.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_cross_gear = QToolButton(self.board)
        self.btn_ff_cross_gear.setObjectName(u"btn_ff_cross_gear")
        self.btn_ff_cross_gear.setGeometry(QRect(315, 20, 71, 61))
        icon11 = QIcon()
        icon11.addFile(u":/img/img/components/cross_gear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_cross_gear.setIcon(icon11)
        self.btn_ff_cross_gear.setIconSize(QSize(65, 35))
        self.btn_ff_cross_gear.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_pinion = QToolButton(self.board)
        self.btn_ff_pinion.setObjectName(u"btn_ff_pinion")
        self.btn_ff_pinion.setGeometry(QRect(390, 20, 71, 61))
        icon12 = QIcon()
        icon12.addFile(u":/img/img/components/pinion.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_pinion.setIcon(icon12)
        self.btn_ff_pinion.setIconSize(QSize(65, 35))
        self.btn_ff_pinion.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_crank_handle = QToolButton(self.board)
        self.btn_ff_crank_handle.setObjectName(u"btn_ff_crank_handle")
        self.btn_ff_crank_handle.setGeometry(QRect(465, 20, 71, 61))
        icon13 = QIcon()
        icon13.addFile(u":/img/img/components/crank_handle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_crank_handle.setIcon(icon13)
        self.btn_ff_crank_handle.setIconSize(QSize(65, 35))
        self.btn_ff_crank_handle.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_ring_gear = QToolButton(self.board)
        self.btn_ff_ring_gear.setObjectName(u"btn_ff_ring_gear")
        self.btn_ff_ring_gear.setGeometry(QRect(540, 20, 71, 61))
        icon14 = QIcon()
        icon14.addFile(u":/img/img/components/ring_gear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_ring_gear.setIcon(icon14)
        self.btn_ff_ring_gear.setIconSize(QSize(65, 35))
        self.btn_ff_ring_gear.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_upper_housing = QToolButton(self.board)
        self.btn_ff_upper_housing.setObjectName(u"btn_ff_upper_housing")
        self.btn_ff_upper_housing.setGeometry(QRect(640, 20, 71, 61))
        icon15 = QIcon()
        icon15.addFile(u":/img/img/components/upper_housing.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_upper_housing.setIcon(icon15)
        self.btn_ff_upper_housing.setIconSize(QSize(65, 35))
        self.btn_ff_upper_housing.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_crank_arm = QToolButton(self.board)
        self.btn_ff_crank_arm.setObjectName(u"btn_ff_crank_arm")
        self.btn_ff_crank_arm.setGeometry(QRect(715, 20, 71, 61))
        icon16 = QIcon()
        icon16.addFile(u":/img/img/components/crank_arm.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_crank_arm.setIcon(icon16)
        self.btn_ff_crank_arm.setIconSize(QSize(65, 35))
        self.btn_ff_crank_arm.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_rotor = QToolButton(self.board)
        self.btn_ff_rotor.setObjectName(u"btn_ff_rotor")
        self.btn_ff_rotor.setGeometry(QRect(790, 20, 71, 61))
        icon17 = QIcon()
        icon17.addFile(u":/img/img/components/rotor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_rotor.setIcon(icon17)
        self.btn_ff_rotor.setIconSize(QSize(65, 35))
        self.btn_ff_rotor.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_pause_all_robots = QToolButton(self.board)
        self.btn_pause_all_robots.setObjectName(u"btn_pause_all_robots")
        self.btn_pause_all_robots.setGeometry(QRect(680, 680, 161, 31))
        font4 = QFont()
        font4.setPointSize(10)
        self.btn_pause_all_robots.setFont(font4)
        self.btn_ff_labeler = QToolButton(self.board)
        self.btn_ff_labeler.setObjectName(u"btn_ff_labeler")
        self.btn_ff_labeler.setGeometry(QRect(3, 378, 71, 61))
        icon18 = QIcon()
        icon18.addFile(u":/img/img/components/barcode.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_labeler.setIcon(icon18)
        self.btn_ff_labeler.setIconSize(QSize(65, 35))
        self.btn_ff_labeler.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.btn_ff_boxing = QToolButton(self.board)
        self.btn_ff_boxing.setObjectName(u"btn_ff_boxing")
        self.btn_ff_boxing.setGeometry(QRect(3, 450, 71, 61))
        icon19 = QIcon()
        icon19.addFile(u":/img/img/components/box.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_ff_boxing.setIcon(icon19)
        self.btn_ff_boxing.setIconSize(QSize(65, 35))
        self.btn_ff_boxing.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.verticalLayout.addWidget(self.board)


        self.retranslateUi(BoardWidget)

        QMetaObject.connectSlotsByName(BoardWidget)
    # setupUi

    def retranslateUi(self, BoardWidget):
        BoardWidget.setWindowTitle(QCoreApplication.translate("BoardWidget", u"Whirl Board", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("BoardWidget", u"Lift && Locate 1", None))
        self.current_5.setText("")
        self.error_5.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("BoardWidget", u"LL2(Grease)", None))
        self.current_grease.setText("")
        self.error_grease.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("BoardWidget", u"Lift && Locate 3", None))
        self.current_1.setText("")
        self.error_1.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("BoardWidget", u"Lift && Locate 4", None))
        self.current_2.setText("")
        self.error_2.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("BoardWidget", u"Lift && Locate 5", None))
        self.current_3.setText("")
        self.error_3.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("BoardWidget", u"Lift && Locate 6", None))
        self.current_4.setText("")
        self.error_4.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("BoardWidget", u"LL7(Final Test)", None))
        self.current_final_test.setText("")
        self.label.setText("")
        self.label_2.setText("")
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("BoardWidget", u"Robot 5", None))
        self.label_7.setText(QCoreApplication.translate("BoardWidget", u"Robot 1", None))
        self.label_8.setText(QCoreApplication.translate("BoardWidget", u"Robot 2", None))
        self.label_9.setText(QCoreApplication.translate("BoardWidget", u"Robot 3", None))
        self.label_10.setText(QCoreApplication.translate("BoardWidget", u"Robot 4", None))
        self.btn_robot_play_5.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_play_1.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_play_2.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_play_3.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_play_4.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_more_1.setText("")
        self.btn_robot_more_2.setText("")
        self.btn_robot_more_3.setText("")
        self.btn_robot_more_4.setText("")
        self.btn_robot_more_5.setText("")
        self.btn_robot_error_1.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_error_2.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_error_3.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_error_4.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_robot_error_5.setText(QCoreApplication.translate("BoardWidget", u"pause", None))
        self.btn_ff_lower_housing.setText(QCoreApplication.translate("BoardWidget", u"L. Housing", None))
        self.btn_ff_left_handle.setText(QCoreApplication.translate("BoardWidget", u"Left Handle", None))
        self.btn_ff_dial.setText(QCoreApplication.translate("BoardWidget", u"Dial", None))
        self.btn_ff_support_arm.setText(QCoreApplication.translate("BoardWidget", u"Support Arm", None))
        self.btn_ff_trigger.setText(QCoreApplication.translate("BoardWidget", u"Trigger", None))
        self.btn_ff_right_handle.setText(QCoreApplication.translate("BoardWidget", u"Right Handle", None))
        self.btn_ff_hopper.setText(QCoreApplication.translate("BoardWidget", u"Hopper", None))
        self.btn_ff_agitator.setText(QCoreApplication.translate("BoardWidget", u"Agitator", None))
        self.btn_ff_cross_gear.setText(QCoreApplication.translate("BoardWidget", u"Cross Gear", None))
        self.btn_ff_pinion.setText(QCoreApplication.translate("BoardWidget", u"Pinion", None))
        self.btn_ff_crank_handle.setText(QCoreApplication.translate("BoardWidget", u"Crank Handle", None))
        self.btn_ff_ring_gear.setText(QCoreApplication.translate("BoardWidget", u"Ring Gear", None))
        self.btn_ff_upper_housing.setText(QCoreApplication.translate("BoardWidget", u"U. Housing", None))
        self.btn_ff_crank_arm.setText(QCoreApplication.translate("BoardWidget", u"Crank Arm", None))
        self.btn_ff_rotor.setText(QCoreApplication.translate("BoardWidget", u"Rotor", None))
        self.btn_pause_all_robots.setText(QCoreApplication.translate("BoardWidget", u"Pause ALL Robots", None))
        self.btn_ff_labeler.setText(QCoreApplication.translate("BoardWidget", u"Labeler", None))
        self.btn_ff_boxing.setText(QCoreApplication.translate("BoardWidget", u"Boxing", None))
    # retranslateUi

